# Generated by Django 5.0.6 on 2024-06-17 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_alter_book_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.bookcategory'),
        ),
        migrations.AlterField(
            model_name='bookcategory',
            name='category',
            field=models.CharField(max_length=50),
        ),
    ]
