# Generated by Django 5.0.6 on 2024-06-17 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_author_age_alter_author_name_alter_book_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
